version: "3"
services:
  web:
    container_name: web
    image: tute7:latest
    ports:
      - 3000:3000
    command: "/usr/app/startup.sh"
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_HOSTNAME=db
      - DB_NAME=app

      

  db:
    container_name: db
    image: postgres:10.7
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=password
    